const ProfilesTypes = {
  RETRIEVE_PROFILE_START: "RETRIEVE_PROFILE_START",
  RETRIEVE_PROFILE_SUCCESS: "RETRIEVE_PROFILE_SUCCESS",
  RETRIEVE_PROFILE_FAILURE: "RETRIEVE_PROFILE_FAILURE",
  UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
  UPLOAD_PHOTO_START: "UPLOAD_PHOTO_START",
  UPLOAD_PHOTO_SUCCESS: "UPLOAD_PHOTO_SUCCESS",
  UPLOAD_PHOTO_FAILURE: "UPLOAD_PHOTO_FAILURE",
  SET_MAIN_PHOTO_START: "SET_MAIN_PHOTO_START",
  SET_MAIN_PHOTO_SUCCESS: "SET_MAIN_PHOTO_SUCCESS",
  SET_MAIN_PHOTO_FAILURE: "SET_MAIN_PHOTO_FAILURE",
  DELETE_PHOTO_START: "DELETE_PHOTO_START",
  DELETE_PHOTO_SUCCESS: "DELETE_PHOTO_SUCCESS",
  DELETE_PHOTO_FAILURE: "DELETE_PHOTO_FAILURE",
};

export default ProfilesTypes;
