const UserTypes = {
  RETRIEVE_USER_START: "RETRIEVE_USER_START",
  RETRIEVE_USER_SUCCESS: "RETRIEVE_USER_SUCCESS",
  RETRIEVE_USER_FAILURE: "RETRIEVE_USER_FAILURE",
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGOUT: "LOGOUT",
  SET_TOKEN: "SET_TOKEN",
  SET_IMAGE: "SET_IMAGE",
};

export default UserTypes;
