const ActivityTypes = {
  FETCH_ACTIVITIES_START: "FETCH_ACTIVITIES_START",
  FETCH_ACTIVITIES_SUCCESS: "FETCH_ACTIVITIES_SUCCESS",
  FETCH_ACTIVITIES_FAILURE: "FETCH_ACTIVITIES_FAILURE",
  CREATE_ACTIVITY_START: "CREATE_ACTIVITY_START",
  CREATE_ACTIVITY_SUCCESS: "CREATE_ACTIVITY_SUCCESS",
  CREATE_ACTIVITY_FAILURE: "CREATE_ACTIVITY_FAILURE",
  EDIT_ACTIVITY_START: "EDIT_ACTIVITY_START",
  EDIT_ACTIVITY_SUCCESS: "EDIT_ACTIVITY_SUCCESS",
  EDIT_ACTIVITY_FAILURE: "EDIT_ACTIVITY_FAILURE",
  DELETE_ACTIVITY_START: "DELETE_ACTIVITY_START",
  DELETE_ACTIVITY_SUCCESS: "DELETE_ACTIVITY_SUCCESS",
  DELETE_ACTIVITY_FAILURE: "DELETE_ACTIVITY_FAILURE",
  SET_SELECTED_ACTIVITY: "SET_SELECTED_ACTIVITY",
  SET_EDIT_MODE: "SET_EDIT_MODE",
  SET_SUBMITTING: "SET_SUBMITTING",
  SET_TARGET: "SET_TARGET",
  OPEN_CREATE_FORM: "OPEN_CREATE_FORM",
};

export default ActivityTypes;
